name: Desktop | CI checks
on:
  push:
    paths-ignore:
      - "packages/landing"
      - "packages/mobile"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -w desktop

      - name: Lint
        run: npm run lint -w desktop
